spring:
  rabbitmq:
    port: 5672
    host : 127.0.0.1
    virtual-host: /tlias
    username: guest
    password: guest
  application:
    name: tlias_study_system
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/db04
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: root
      database: 0
      lettuce:
        pool:
          max-active: 20
          max-idle: 5
          min-idle: 0
          max-wait: 1000ms
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.tlias_study_system.pojo